apiVersion: apps/v1
kind: ReplicaSet
metadata: 
  name: frontend-rs
  labels:
    name: frontend
spec: 
  replicas: 3
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      name: nginx-pod
      labels:
        name: frontend
    spec:
      containers:
      - name: myapp
        image: nginx
        resources:  
          limits:
            memory: "128Mi"
            cpu: "500m"

