apiVersion: api/v1
kind: ReplicaSet
metadata: 
  name: frontend-rs
  labels:
    name: frontend
spec: 
  metadata:
  name: nginx-pod
  labels:
    name: frontend
  spec:
    containers:
    - name: myapp
      image: nginx